[package]
name = "gistcard"
version = "0.1.0"
authors = ["Mike Engel <mike@mike-engel.com>"]
edition = "2018"

[dependencies]
regex = "1"
log = "0.4"
reqwest = "0.9"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
http = "0.1"
html5ever = "0.23"
